# firewall-operator-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: firewall-operator
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: firewall-operator
  template:
    metadata:
      labels:
        app: firewall-operator
    spec:
      serviceAccountName: firewall-operator
      hostNetwork: true
      hostPID: true
      containers:
      - name: firewall-operator
        image: myrepo/firewall-operator:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: ufw
          mountPath: /etc/ufw
        - name: iptables
          mountPath: /etc/iptables
        - name: var-log-ufw
          mountPath: /var/log/ufw.log
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: true
      volumes:
      - name: ufw
        hostPath:
          path: /etc/ufw
      - name: iptables
        hostPath:
          path: /etc/iptables
      - name: var-log-ufw
        hostPath:
          path: /var/log/ufw.log
      - name: proc
        hostPath:
          path: /proc
