# firewall-operator-rbac.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: firewall-operator
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewall-operator
rules:
  - apiGroups: [""]
    resources: ["nodes", "events", "namespaces", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["my.firewall"]
    resources: ["firewallrules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["my.firewall"]
    resources: ["firewallrules/status"]
    verbs: ["get", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: firewall-operator
subjects:
  - kind: ServiceAccount
    name: firewall-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: firewall-operator
  apiGroup: rbac.authorization.k8s.io
